### ISSUE TITLE
Lite indenterings-kaos i index.html

### ISSUE THREAD

**Issue by kallqvist** [sarakallqvist/myfirstwebpage#1]
Hej, fin hemsida!

Jag har hittat lite oregelbundna indenteringar i [index.html] (https://github.com/sarakallqvist/myfirstwebpage/blob/main/First-website/index.html#L13).

Håller på att åtgärda dem så kan tänka mig att skapa en pull request om ingen annan arbetar på detta?

**Comment by kallqvist** [comment]
Jag har skapat en pull request #2

**Comment by sarakallqvist** [comment]
Jag har accepterat dina ändringar och mergeat nu. Hur hamnar det här tillbaka i min VS? :) Dags för nästa uppgift nämligen.
